apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: devops-platform-db-secret
  namespace: default
spec:
  encryptedData:
    postgres-password: AgBPUXGVzXbyW15XS458CWQql6dEFPchE2GUWBQ+5zhAsDOp9ppz3ABmOCOYElQLO530Ebbc3TiVJOnhvUDlE06UDQsHri4a8dDVbCv6A/WiJ7WpJfSy2yBqLnUjdB9jU5WFTOlXTPyxJ+xreFkN1Qn79CCYf1hmbUE/hORg6gwHccUY/KzBoEMaQl4cXbic4dUeFV77BA5WCaY6UIVOAjUfX2tWeBG4fMrNRhi66S/BCrUVZaCjREO8/XqmXui4c1Q5j1hkge+Qnc5zOvM2C7rdAwxBbKveLXN0VcySHCWsZtfFVMbwjbO2ADp50bV7L9YgE4zrKlXFWFbnLI4iyevSzyIxy3mbxr4JBDzX+FSwq2di0+7IVYwTHnV8HdtZneOJFyxG+nC2n9kT9J7vIx8Uz5VfVtPu9vMwLXU6BIFucSQFnVLlkdJ74lG4QNmsUHIUiDRUkHTlTj5vMXbh2uKThgIq5dRRrPtFHJRi35t3ZCSBOyxgF9QUKRVulpSmJyHAVkAGldc9UnGsnYQzkjMah5YV3XE3JLsfmtK3FUvtdLLYR0YCfhxo2E8IzIMUEY2VQpAH52JL66Nn6Op7SmtzVKg8Lq+0HAN3bBEBdGWQ/L9ORoPruQXxWET8w4MVLYRbRdy9IpQ1cpsYdueE3gTjSKvFANe4ZCcbruN2LLw9VIseDh0x0ArqrrlgsDJX24JiqU21u5uHZa2SAg==
  template:
    metadata:
      creationTimestamp: null
      name: devops-platform-db-secret
      namespace: default
    type: Opaque

