apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: devops-platform-db-secret
  namespace: default
spec:
  encryptedData:
    postgres-password: AgDPzdyfxNfDj9iGhB9jKpjwWMHUZmq/Fj7K/O68ODUxwuq4+fdE98NcBiKUQ/dypFNN+3FRme5vcyPa4G2AskCPF6C00AikA7CNwXYouoZM9gsHok49F2anqnaVQklrjPLVZxG2TbXi5/vuuu/NuWogbH2RliAY9joM45hvmM1Bd0BWopNrn4EPrfq8GAu3Q9Hdth8Vz0HZ0pz/YBSYOpEn4stSb8ODP6xxauWndrl54IE4gBJoMtjMMV85LjHJsozYqs0y/GmxFoiNeiZ3g/QX4unt/gmSw+v8Kd+bpiSKWWuqjvKAJ08gxMqsXT9ZFWFwLC7huqhX1743P9K8nmEVl6H4Pu0l6mWGFL5EMausy3x4FJ2FMSQgE8qWYIlPbH1FLNy1iodx7VWXP7dJ832djoqkHE/xse2uX5fZCAyUjjPTnrVDrF6+akx0hB8b5S12DRgyPbIEsdyzI6Nj8Ec16+yJJiTWBtH/p5wueKLx9Wi435/brKp+ZVsF4QHKRrul6OjSYT2FDNfS7m9rYiKzhMxT8Va4HPitXyqjdVB+nTk/RL1DQD/8Jku26tDq31/P4lTufVllAYBL0bigyN2kzax2rLIwI2QZfMylS5gOfb/hi1sPNzAjTjEe71gPya6qhqiJMMow58xq1yH0EKJLSMBzLf7lQrsAHEzs5mmj5OjS65J1mgwIGqppkC3znW+d6cIcC7pWIxGCVw==
  template:
    metadata:
      creationTimestamp: null
      name: devops-platform-db-secret
      namespace: default
    type: Opaque

